### PR TITLE
Refactor tests for venue feature

### PR DESCRIPTION
**Pull request by nataniadeandra**

### CODE REVIEW

**Comment by nataniadeandra** [comment]
image

**Review by JohannesSetiawan — APPROVED** [review]
The refactor makes the test more readable.

**Review by catherineeangel — APPROVED** [review]
LGTM

**Comment by swastikanata** [comment]
So far the code and tests look good

**Comment by emiriko** [comment]
Looks nice!

**Review by swastikanata — COMMENTED** [review]
So far the code and tests look good

**Pull request merged**
