### PR TITLE
Bugfix on Shorten Token and See Task List

### PR DESCRIPTION
**Pull request by JohannesSetiawan**
What changes:
- Make sure every token request is can be done even without submitting the forms in create_shortened_token()
- Fix bug so the task list fill list all task associated with an event only.

### CODE REVIEW

**Review by emiriko — CHANGES_REQUESTED** [review]
To merge, we will have to make sure all the workflows went through. I think there is an issue with OpenAI secrets. But overall the implementation of your code looks good.

**Review by nataniadeandra — CHANGES_REQUESTED** [review]
I agree with Alvaro, it looks like there might be an issue with OpenAI secrets. Let's make sure to address that before proceeding with the merge. Also, pulling from the staging branch and rerunning any failed jobs would be a good idea to ensure everything is functioning properly.

**Comment by JohannesSetiawan** [comment]
Done, workflows success

**Review by emiriko — APPROVED** [review]
Good job Jonathan for the work, I think this feature is going to be a great addition.

**Review by nataniadeandra — APPROVED** [review]
All good now!

**Pull request merged**
