### PR TITLE
Add deployment to production environtment

### PR DESCRIPTION
**Pull request by JohannesSetiawan**
What changes/added:
-) Add new workflows for deploying on GCP VM
-) Fix Dockerfile
-) Add new env variabels for Midtrans
-) Fix CORS issue for production frontend

### CODE REVIEW

**Review by catherineeangel — APPROVED** [review]
LGTM

**Review by emiriko — APPROVED** [review]
Good job Jo! One question though, why do you allow localhost:3001 on CORS? I thought localhost:3000 alone would be enough.

**Comment by JohannesSetiawan** [comment]
> Good job Jo! One question though, why do you allow localhost:3001 on CORS? I thought localhost:3000 alone would be enough.

Someone on our team got its front end on port 3001 while running on their own device.

**Comment by emiriko** [comment]
> > Good job Jo! One question though, why do you allow localhost:3001 on CORS? I thought localhost:3000 alone would be enough.
> 
> Someone on our team got its front end on port 3001 while running on their own device.

Oh right, thank you for the clarification.

**Pull request merged**
