### PR TITLE
Add Feature to Delete All Rundown

### PR DESCRIPTION
**Pull request by swastikanata**

### CODE REVIEW

**Review by catherineeangel — APPROVED** [review]
LGTM!

**Review by JohannesSetiawan — APPROVED** [review]
Good implementation. LGTM!

**Review by carlenee — APPROVED** [review]
Great job implementing the code, I have a few suggestions for future use.

Suggestions for Improvement:

	•	Error Handling: It might be beneficial to add error handling for scenarios where the event_id does not exist or is invalid, to return a more descriptive error message.
	•	Confirmation Mechanism: For safety, consider implementing a confirmation step before performing the deletion, or a way to recover deleted data in case of accidental deletions.

**Review by emiriko — APPROVED** [review]
The implementation is nice, but next time you can try to give brief descriptions of what you have worked on. Good job though!

**Pull request merged**
